### ISSUE TITLE
Weight consideration of each box

### ISSUE THREAD

**Issue by cariquitanmac** [betterwaysystems/packer#3]
Hi Sir,

Do you have any idea how to consider the weight of each box? In such a way that heavier boxes should be on the bottom and the lighter would be on the top.

**Comment by samchon** [comment]
My **packer** is using the algorithm: *THE DISTRIBUTER'S THREE-DIMENSIONAL PALLET-PACKING PROBLEM: A HUMAN INTELLIGENCE-BASED HEURISTIC APPROACH*
  - http://betterwaysystems.github.io/packer/reference/AirForceBinPacking.pdf

The paper doesn't consider the weight, so it's hard for me to implementing the conception *weight*. 
About the weight, how about using this?
  - https://github.com/mushishi78/box_packer

**Comment by cariquitanmac** [comment]
Thanks for the response, I am using the same algo and added weight constraint support by prioritizing the heavier objects first but the only downside is it leaving big gaps between boxes.
I will take a look on the link you have given.
