### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by deadeye636** [betterwaysystems/packer#4]
Hi @samchon 
I am trying to implement for an test application but iam unable to get your example to work.

iam not a ts or c++ dev. perhaps you could help me in understanding how your application is working.
if i get it work i want to create a linux shell application wich will read a file with the data and output it to a file.

thank you.

**Comment by samchon** [comment]
I'm on vacation. I will help you at next week.

**Comment by samchon** [comment]
First, make a JavaScript file (I named it `packer.js`) and write the below code:

```js
var fs = require("fs");
var samchon = require("samchon-framework");
var library = samchon.library;

var pack = require("3d-bin-packing");

function main(inputPath, outputPath)
{
	var input_str = fs.readFileSync(inputPath, "utf8");
	var input_xml = new library.XML(input_str);

	var packer = new pack.PackerForm();
	packer.construct(input_xml);
	
	var result = packer.optimize();
	var output_str = result.toXML().toString();
	fs.writeFileSync(outputPath, output_str, "utf8");
}
main(process.argv[2], process.argv[3]);
```

Call the `packer.js` via node, with two parameters, input and output files.
```bash
node packer input.xml output.xml
```

**Comment by deadeye636** [comment]
Hi @samchon ,

thank you for the example. got it working now and it looks realy great.

is there perhaps some explation for<gaParameters generation="500" population="100" tournament="50" mutationRate="0.2"/>?

**Comment by samchon** [comment]
@deadeye636 Well, which explanation do you want?

**Comment by deadeye636** [comment]
mhh nice there is missing some word.
iam trying to understand what is the best for the gaParameters.

iam trying to get the lowest count for the bins. but at the moment iam getting 2x small bins but 1x middle bin would be better.

thanks
