### ISSUE TITLE
Get wrapper products in JSON format

### ISSUE THREAD

**Issue by ScottShannon** [betterwaysystems/packer#7]
I am not able to find any method for getting products from a given wrapper.  I see that the demo has the ability to do this.  Is there any way to accomplish this in JSON format?  Thanks.

**Comment by samchon** [comment]
Packer provides XML, not JSON.

Reference below code:
- https://github.com/betterwaysystems/packer/blob/master/ts/src/bws/packer/ResultViewer.tsx#L52

**Comment by ScottShannon** [comment]
I found a solution, looping through 2 levels of the packer result using the at() method let's you build it in json

**Comment by samchon** [comment]
Well, there're lots of cross dependencies in this Packer. 

So I designed packer to use XML structure. I recommend you to use the XML structure.
If you must use the JSON structure, then you should make your own adaptor module.
