### ISSUE TITLE
Strange Result for same Data

### ISSUE THREAD

**Issue by alexschled** [betterwaysystems/packer#8]
Hello,

I just tried your BoxPacker, but unfortunately I can't understand the result for following two XML files:

`<packerForm>
	<instanceFormArray>
		<instanceForm count="24">
			<instance name="Item1" width="9.5" height="9.5" length="10" type="product" />
		</instanceForm>
		<instanceForm count="12">
			<instance name="Item2" width="17.5" height="17.5" length="21.5" type="product" />
		</instanceForm>
		<instanceForm count="2">
			<instance name="Item3" width="10.25" height="10.83" length="16.3" type="product" />
		</instanceForm>
		<instanceForm count="6">
			<instance name="Item" width="9.5" height="18" length="6.08" type="product" />
		</instanceForm>
	</instanceFormArray>
	<wrapperArray>
		<instance name="Large" price="102" width="59" height="59" length="40.5" thickness="0" type="wrapper" />
		<instance name="Middle" price="101" width="58" height="29" length="40.5" thickness="0" type="wrapper" />
		<instance name="Small" price="100" width="40.5" height="29" length="29" thickness="0" type="wrapper" />
	</wrapperArray>
</packerForm>`

And the same file here, only the position of the Items has changed:

`<packerForm><instanceFormArray> <instanceForm count="12"><instance name=„Item2" width="1750" height="1750" length="2150" type="product" /></instanceForm><instanceForm count="2"><instance name=„Item3" width="1025" height="1630" length="1083" type="product" /></instanceForm><instanceForm count="24"><instance name=„Item1" width="950" height="1500" length="1500" type="product" /></instanceForm><instanceForm count="6"><instance name=„Item4" width="950" height="1800" length="608" type="product" /></instanceForm>
<wrapperArray><instance name=„Large" width="5900" price="102" height="5900" length="4050" thickness="0" type="wrapper" /><instance name=„Small" width="4050" price="100" height="2900" length="2900" thickness="0" type="wrapper" /><instance name=„Middle" width="5800" price="101" height="2900" length="4050" thickness="0" type="wrapper" /></wrapperArray></packerForm>`

The result is a different:

With the first XML the Items fits into one large Box.
With the second XML the system suggest a big one and 2 small boxes

Why is this?

**Comment by samchon** [comment]
Because the `item1` of top and bottom are different.

Category      | Width | Height | Length
--------------|--------|---------|---------
Top              | 9.50    | 9.5       | 10.0
Bottom        | 950     | 1500    | 1500
